const anyNumber = { bsonType: ['decimal', 'double', 'int', 'long'] };
const optionalNumber = { bsonType: ['decimal', 'double', 'int', 'long', 'null'] };
const string = { bsonType: 'string' };
const optionalString = { bsonType: ['string', 'null'] };
const date = { bsonType: 'date' };
const optionalDate = { bsonType: ['date', 'null'] };
const bool = { bsonType: 'bool' };
const optionalBool = { bsonType: ['bool', 'null'] };
const object = { bsonType: 'object' };
const optionalObject = { bsonType: ['object', 'null'] };
const array = { bsonType: 'array' };
const optionalArray = { bsonType: ['array', 'null'] };

function schema(required, properties) {
  return {
    $jsonSchema: {
      bsonType: 'object',
      required: ['_id', ...required],
      additionalProperties: true,
      properties: {
        _id: string,
        ...properties,
      },
    },
  };
}

function createOrUpdateCollection(name, validator) {
  if (db.getCollectionNames().includes(name)) {
    db.runCommand({ collMod: name, validator, validationLevel: 'moderate', validationAction: 'warn' });
    return;
  }

  db.createCollection(name, { validator, validationLevel: 'moderate', validationAction: 'warn' });
}

const collections = [
  {
    name: 'users',
    required: ['email'],
    properties: {
      name: optionalString,
      email: string,
      emailVerified: optionalDate,
      image: optionalString,
      password: optionalString,
      phone: optionalString,
      customer_code: optionalString,
      created_at: optionalDate,
      updated_at: optionalDate,
      role: { enum: ['customer', 'admin', 'staff', null] },
      password_hash: optionalString,
    },
  },
  {
    name: 'accounts',
    required: ['userId', 'type', 'provider', 'providerAccountId'],
    properties: {
      userId: string,
      type: string,
      provider: string,
      providerAccountId: string,
      refresh_token: optionalString,
      access_token: optionalString,
      expires_at: { bsonType: ['long', 'int', 'null'] },
      token_type: optionalString,
      scope: optionalString,
      id_token: optionalString,
      session_state: optionalString,
      encrypted_refresh_token: optionalString,
      encrypted_access_token: optionalString,
      encrypted_id_token: optionalString,
    },
  },
  {
    name: 'sessions',
    required: ['sessionToken', 'userId', 'expires'],
    properties: {
      sessionToken: string,
      userId: string,
      expires: date,
      ip_address: optionalString,
      user_agent: optionalString,
      last_seen_at: optionalDate,
    },
  },
  {
    name: 'verification_tokens',
    required: ['identifier', 'token', 'expires'],
    properties: {
      identifier: string,
      token: string,
      expires: date,
    },
  },
  {
    name: 'password_reset_tokens',
    required: ['user_id', 'token_hash', 'expires_at'],
    properties: {
      user_id: string,
      token_hash: string,
      expires_at: date,
      created_at: optionalDate,
      consumed_at: optionalDate,
    },
  },
  {
    name: 'user_profiles',
    required: ['user_id'],
    properties: {
      user_id: string,
      full_name: optionalString,
      phone: optionalString,
      avatar_url: optionalString,
      created_at: optionalDate,
      updated_at: optionalDate,
    },
  },
  {
    name: 'user_addresses',
    required: ['user_id', 'full_name', 'phone', 'address_line'],
    properties: {
      user_id: string,
      full_name: string,
      phone: string,
      province: optionalString,
      district: optionalString,
      ward: optionalString,
      address_line: string,
      is_default: optionalBool,
      created_at: optionalDate,
    },
  },
  {
    name: 'categories',
    required: ['name'],
    properties: {
      name: string,
      parent_id: optionalString,
      sort_order: { bsonType: ['int', 'long', 'null'] },
      is_active: optionalBool,
      created_at: optionalDate,
      description: optionalString,
    },
  },
  {
    name: 'products',
    required: ['name'],
    properties: {
      category_id: optionalString,
      sku: optionalString,
      name: string,
      base_price: anyNumber,
      sale_price: optionalNumber,
      stock: { bsonType: ['int', 'long', 'null'] },
      images: optionalArray,
      specs: optionalObject,
      is_active: optionalBool,
      view_count: { bsonType: ['int', 'long', 'null'] },
      sold_count: { bsonType: ['int', 'long', 'null'] },
      created_at: optionalDate,
      updated_at: optionalDate,
      description: optionalString,
      short_description: optionalString,
      is_featured: optionalBool,
      tags: optionalArray,
      low_stock_alert: { bsonType: ['int', 'long', 'null'] },
      sizes: optionalArray,
      archived_at: optionalDate,
    },
  },
  {
    name: 'product_variants',
    required: ['product_id', 'name', 'price'],
    properties: {
      product_id: string,
      sku: optionalString,
      name: string,
      price: anyNumber,
      stock: { bsonType: ['int', 'long'] },
      image_url: optionalString,
      images: optionalArray,
      is_active: optionalBool,
      sort_order: { bsonType: ['int', 'long', 'null'] },
      created_at: optionalDate,
      updated_at: optionalDate,
      reserved_stock: { bsonType: ['int', 'long', 'null'] },
    },
  },
  {
    name: 'orders',
    required: ['order_code'],
    properties: {
      order_code: string,
      user_id: optionalString,
      subtotal: optionalNumber,
      discount: optionalNumber,
      total_amount: optionalNumber,
      deposit_amount: optionalNumber,
      order_type: { enum: ['product', 'custom', 'printing', 'ready_made', null] },
      status: { enum: ['pending', 'confirmed', 'designing', 'awaiting_approval', 'approved', 'printing', 'shipped', 'completed', 'cancelled', null] },
      payment_status: { enum: ['pending', 'partial', 'paid', 'failed', 'refunded', null] },
      created_at: optionalDate,
      updated_at: optionalDate,
      confirmed_at: optionalDate,
      paid_at: optionalDate,
      shipped_at: optionalDate,
      completed_at: optionalDate,
      approved_at: optionalDate,
      shipping_code: optionalString,
      archived_at: optionalDate,
      fulfillment_status: { enum: ['pending', 'processing', 'fulfilled', 'cancelled', null] },
      shipping_address_snapshot: optionalObject,
      notes: optionalString,
      admin_notes: optionalString,
      demo_images: optionalArray,
      finished_images: optionalArray,
      revision_count: { bsonType: ['int', 'long', 'null'] },
      revision_feedback: optionalString,
      shipping_fee: optionalNumber,
      outstanding_amount: optionalNumber,
    },
  },
  {
    name: 'order_addresses',
    required: ['order_id', 'full_name', 'phone', 'address_line'],
    properties: {
      order_id: string,
      full_name: string,
      phone: string,
      province: optionalString,
      district: optionalString,
      ward: optionalString,
      address_line: string,
    },
  },
  {
    name: 'order_items',
    required: ['order_id', 'item_code', 'full_code', 'name'],
    properties: {
      order_id: string,
      product_id: optionalString,
      item_code: string,
      full_code: string,
      name: string,
      sku: optionalString,
      quantity: { bsonType: ['int', 'long'] },
      unit_price: anyNumber,
      item_type: { enum: ['product', 'custom', 'printing', null] },
      production_status: { enum: ['waiting', 'designing', 'printing', 'done', 'cancelled', null] },
      created_at: optionalDate,
      total_price: optionalNumber,
      configuration: optionalObject,
      product_variant_id: optionalString,
    },
  },
  {
    name: 'files',
    required: ['file_url'],
    properties: {
      file_url: string,
      mime_type: optionalString,
      size_bytes: { bsonType: ['long', 'int', 'null'] },
      provider: { enum: ['r2', 'drive', 's3', 'local', null] },
      created_at: optionalDate,
      checksum_sha256: optionalString,
      original_filename: optionalString,
      object_key: optionalString,
    },
  },
  {
    name: 'file_links',
    required: ['file_id', 'ref_id'],
    properties: {
      file_id: string,
      ref_type: { enum: ['order', 'order_item', 'revision', null] },
      ref_id: string,
      tag: optionalString,
      created_at: optionalDate,
      metadata: optionalObject,
    },
  },
  {
    name: 'order_files',
    required: ['order_id', 'file_id'],
    properties: {
      order_id: string,
      file_id: string,
      tag: optionalString,
      metadata: object,
      created_at: optionalDate,
    },
  },
  {
    name: 'order_item_files',
    required: ['order_item_id', 'file_id'],
    properties: {
      order_item_id: string,
      file_id: string,
      tag: optionalString,
      metadata: object,
      created_at: optionalDate,
    },
  },
  {
    name: 'order_notes',
    required: ['order_id', 'content'],
    properties: {
      order_id: string,
      author_id: optionalString,
      content: string,
      type: { enum: ['customer', 'admin', 'system', null] },
      created_at: optionalDate,
      updated_at: optionalDate,
    },
  },
  {
    name: 'order_revisions',
    required: ['order_id', 'version'],
    properties: {
      order_id: string,
      version: { bsonType: ['int', 'long'] },
      status: { enum: ['pending', 'approved', 'rejected', null] },
      feedback: optionalString,
      created_at: optionalDate,
    },
  },
  {
    name: 'revision_files',
    required: ['order_revision_id', 'file_id'],
    properties: {
      order_revision_id: string,
      file_id: string,
      tag: optionalString,
      metadata: object,
      created_at: optionalDate,
    },
  },
  {
    name: 'order_status_history',
    required: ['order_id'],
    properties: {
      order_id: string,
      status: optionalString,
      changed_at: optionalDate,
    },
  },
  {
    name: 'design_versions',
    required: ['order_id', 'version_number', 'status'],
    properties: {
      order_id: string,
      version_number: { bsonType: ['int', 'long'] },
      status: { enum: ['pending_review', 'approved', 'rejected'] },
      admin_note: optionalString,
      user_feedback: optionalString,
      created_at: optionalDate,
      reviewed_at: optionalDate,
    },
  },
  {
    name: 'design_images',
    required: ['version_id', 'image_url'],
    properties: {
      version_id: string,
      image_url: string,
      label: optionalString,
      sort_order: { bsonType: ['int', 'long', 'null'] },
      created_at: optionalDate,
    },
  },
  {
    name: 'notifications',
    required: ['user_id', 'title', 'type'],
    properties: {
      user_id: string,
      title: string,
      message: optionalString,
      type: { enum: ['design_approved', 'design_rejected', 'design_uploaded', 'order_status', 'payment'] },
      is_read: bool,
      ref_id: optionalString,
      ref_type: { enum: ['order', 'design_version', null] },
      created_at: optionalDate,
      read_at: optionalDate,
      ref_order_id: optionalString,
      ref_design_version_id: optionalString,
      ref_payment_id: optionalString,
    },
  },
  {
    name: 'payments',
    required: ['order_id', 'amount'],
    properties: {
      order_id: string,
      transaction_code: optionalString,
      amount: anyNumber,
      method: optionalString,
      status: { enum: ['pending', 'partial', 'paid', 'failed', 'refunded', null] },
      gateway_response: optionalObject,
      created_at: optionalDate,
      confirmed_at: optionalDate,
    },
  },
  {
    name: 'payment_events',
    required: ['payment_id'],
    properties: {
      payment_id: string,
      event_type: optionalString,
      payload: optionalObject,
      created_at: optionalDate,
    },
  },
  {
    name: 'payment_configs',
    required: ['order_type', 'bank_code', 'account_no', 'account_name'],
    properties: {
      order_type: { enum: ['ready_made', 'custom', 'printing'] },
      bank_code: string,
      account_no: string,
      account_name: string,
      is_active: optionalBool,
      notes: optionalString,
      updated_at: optionalDate,
      created_at: optionalDate,
    },
  },
  {
    name: 'print_jobs',
    required: ['order_item_id'],
    properties: {
      order_item_id: string,
      material: optionalString,
      color: optionalString,
      infill: { bsonType: ['int', 'long', 'null'] },
      layer_height: optionalNumber,
      estimated_hours: optionalNumber,
      estimated_grams: optionalNumber,
      status: { enum: ['waiting', 'printing', 'paused', 'completed', 'failed', null] },
      created_at: optionalDate,
      started_at: optionalDate,
      completed_at: optionalDate,
      updated_at: optionalDate,
    },
  },
  {
    name: 'activity_logs',
    required: [],
    properties: {
      user_id: optionalString,
      action: optionalString,
      metadata: optionalObject,
      created_at: optionalDate,
    },
  },
  {
    name: 'admin_audit_log',
    required: ['admin_id', 'action', 'resource_type'],
    properties: {
      admin_id: string,
      action: string,
      resource_type: string,
      resource_id: optionalString,
      details: optionalObject,
      ip_address: optionalString,
      user_agent: optionalString,
      created_at: optionalDate,
    },
  },
  {
    name: 'system_settings',
    required: ['key', 'value'],
    properties: {
      key: string,
      value: {},
      label: optionalString,
      description: optionalString,
      group_name: optionalString,
      is_public: optionalBool,
      created_at: optionalDate,
      updated_at: optionalDate,
    },
  },
];

const indexes = [
  ['users', { email: 1 }, { unique: true, name: 'users_email_unique' }],
  ['users', { customer_code: 1 }, { unique: true, sparse: true, name: 'users_customer_code_unique' }],
  ['users', { role: 1 }, { name: 'users_role_idx' }],
  ['accounts', { provider: 1, providerAccountId: 1 }, { unique: true, name: 'accounts_provider_account_unique' }],
  ['accounts', { userId: 1 }, { name: 'accounts_user_idx' }],
  ['sessions', { sessionToken: 1 }, { unique: true, name: 'sessions_token_unique' }],
  ['sessions', { userId: 1 }, { name: 'sessions_user_idx' }],
  ['sessions', { expires: 1 }, { expireAfterSeconds: 0, name: 'sessions_expires_ttl' }],
  ['verification_tokens', { identifier: 1, token: 1 }, { unique: true, name: 'verification_identifier_token_unique' }],
  ['verification_tokens', { expires: 1 }, { expireAfterSeconds: 0, name: 'verification_expires_ttl' }],
  ['password_reset_tokens', { user_id: 1 }, { unique: true, name: 'password_reset_user_unique' }],
  ['password_reset_tokens', { token_hash: 1 }, { unique: true, name: 'password_reset_token_unique' }],
  ['password_reset_tokens', { expires_at: 1 }, { expireAfterSeconds: 0, name: 'password_reset_expires_ttl' }],
  ['user_profiles', { user_id: 1 }, { unique: true, name: 'user_profiles_user_unique' }],
  ['user_addresses', { user_id: 1, is_default: 1 }, { name: 'user_addresses_default_idx' }],
  ['categories', { parent_id: 1, sort_order: 1 }, { name: 'categories_parent_sort_idx' }],
  ['categories', { is_active: 1, sort_order: 1 }, { name: 'categories_active_sort_idx' }],
  ['products', { sku: 1 }, { unique: true, sparse: true, name: 'products_sku_unique' }],
  ['products', { category_id: 1, is_active: 1 }, { name: 'products_category_active_idx' }],
  ['products', { is_featured: 1, is_active: 1 }, { name: 'products_featured_active_idx' }],
  ['products', { name: 'text', description: 'text', short_description: 'text', tags: 'text' }, { name: 'products_text_search_idx' }],
  ['product_variants', { product_id: 1, sort_order: 1 }, { name: 'product_variants_product_sort_idx' }],
  ['product_variants', { sku: 1 }, { unique: true, sparse: true, name: 'product_variants_sku_unique' }],
  ['orders', { order_code: 1 }, { unique: true, name: 'orders_order_code_unique' }],
  ['orders', { user_id: 1, created_at: -1 }, { name: 'orders_user_created_idx' }],
  ['orders', { status: 1, created_at: -1 }, { name: 'orders_status_created_idx' }],
  ['orders', { payment_status: 1, created_at: -1 }, { name: 'orders_payment_created_idx' }],
  ['orders', { fulfillment_status: 1, created_at: -1 }, { name: 'orders_fulfillment_created_idx' }],
  ['orders', { archived_at: 1 }, { name: 'orders_archived_idx' }],
  ['order_addresses', { order_id: 1 }, { unique: true, name: 'order_addresses_order_unique' }],
  ['order_items', { order_id: 1 }, { name: 'order_items_order_idx' }],
  ['order_items', { full_code: 1 }, { unique: true, name: 'order_items_full_code_unique' }],
  ['order_items', { product_id: 1 }, { sparse: true, name: 'order_items_product_idx' }],
  ['files', { file_url: 1 }, { unique: true, name: 'files_url_unique' }],
  ['files', { object_key: 1 }, { unique: true, sparse: true, name: 'files_object_key_unique' }],
  ['files', { checksum_sha256: 1 }, { sparse: true, name: 'files_checksum_idx' }],
  ['file_links', { file_id: 1 }, { name: 'file_links_file_idx' }],
  ['file_links', { ref_type: 1, ref_id: 1, tag: 1 }, { name: 'file_links_ref_idx' }],
  ['order_files', { order_id: 1 }, { name: 'order_files_order_idx' }],
  ['order_files', { file_id: 1 }, { name: 'order_files_file_idx' }],
  ['order_item_files', { order_item_id: 1 }, { name: 'order_item_files_item_idx' }],
  ['order_item_files', { file_id: 1 }, { name: 'order_item_files_file_idx' }],
  ['order_notes', { order_id: 1, created_at: -1 }, { name: 'order_notes_order_created_idx' }],
  ['order_revisions', { order_id: 1, version: -1 }, { unique: true, name: 'order_revisions_order_version_unique' }],
  ['revision_files', { order_revision_id: 1 }, { name: 'revision_files_revision_idx' }],
  ['order_status_history', { order_id: 1, changed_at: -1 }, { name: 'order_status_history_order_changed_idx' }],
  ['design_versions', { order_id: 1, version_number: -1 }, { unique: true, name: 'design_versions_order_version_unique' }],
  ['design_versions', { status: 1, created_at: -1 }, { name: 'design_versions_status_created_idx' }],
  ['design_images', { version_id: 1, sort_order: 1 }, { name: 'design_images_version_sort_idx' }],
  ['notifications', { user_id: 1, is_read: 1, created_at: -1 }, { name: 'notifications_user_read_created_idx' }],
  ['notifications', { ref_type: 1, ref_id: 1 }, { sparse: true, name: 'notifications_ref_idx' }],
  ['payments', { order_id: 1 }, { name: 'payments_order_idx' }],
  ['payments', { transaction_code: 1 }, { unique: true, sparse: true, name: 'payments_transaction_unique' }],
  ['payments', { status: 1, created_at: -1 }, { name: 'payments_status_created_idx' }],
  ['payment_events', { payment_id: 1, created_at: -1 }, { name: 'payment_events_payment_created_idx' }],
  ['payment_configs', { order_type: 1 }, { unique: true, name: 'payment_configs_order_type_unique' }],
  ['print_jobs', { order_item_id: 1 }, { unique: true, name: 'print_jobs_order_item_unique' }],
  ['print_jobs', { status: 1, updated_at: -1 }, { name: 'print_jobs_status_updated_idx' }],
  ['activity_logs', { user_id: 1, created_at: -1 }, { name: 'activity_logs_user_created_idx' }],
  ['activity_logs', { action: 1, created_at: -1 }, { name: 'activity_logs_action_created_idx' }],
  ['admin_audit_log', { admin_id: 1, created_at: -1 }, { name: 'admin_audit_admin_created_idx' }],
  ['admin_audit_log', { resource_type: 1, resource_id: 1, created_at: -1 }, { name: 'admin_audit_resource_created_idx' }],
  ['system_settings', { key: 1 }, { unique: true, name: 'system_settings_key_unique' }],
  ['system_settings', { group_name: 1, is_public: 1 }, { name: 'system_settings_group_public_idx' }],
];

for (const collection of collections) {
  createOrUpdateCollection(collection.name, schema(collection.required, collection.properties));
}

for (const [collectionName, keys, options] of indexes) {
  db.getCollection(collectionName).createIndex(keys, options);
}

printjson({ ok: true, database: db.getName(), collections: collections.length, indexes: indexes.length });
